# Generated by Django 3.1 on 2020-08-26 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0017_auto_20200825_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.traineeprofile')),
            ],
        ),
    ]
