# Generated by Django 3.1 on 2020-08-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='reason',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
