# Generated by Django 3.1 on 2020-08-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainee_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.BigIntegerField(max_length=10)),
                ('image', models.ImageField(max_length=255, upload_to='')),
            ],
        ),
    ]
