# Generated by Django 3.1 on 2020-08-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_trainee_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trainee_profile',
            new_name='TraineeProfile',
        ),
    ]
