# Generated by Django 3.1 on 2020-08-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200819_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeprofile',
            name='age',
            field=models.DateField(),
        ),
    ]
