# Generated by Django 3.1 on 2020-08-19 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0004_auto_20200819_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traineeprofile',
            name='address',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='traineeprofile',
            name='age',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='traineeprofile',
            name='image',
            field=models.ImageField(default='images/profile.jpd', max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='traineeprofile',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='traineeprofile',
            name='phone',
            field=models.BigIntegerField(default=None, max_length=10),
        ),
    ]
