# Generated by Django 3.1 on 2020-08-19 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0008_auto_20200819_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeprofile',
            name='user',
            field=models.OneToOneField(default=9, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
