# Generated by Django 3.1 on 2020-08-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20200819_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_dept_lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=300)),
                ('phone', models.BigIntegerField(max_length=12)),
                ('email', models.EmailField(max_length=25)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='phone',
            field=models.BigIntegerField(max_length=12),
        ),
    ]
