# Generated by Django 3.1 on 2020-08-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20200821_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='phone',
            field=models.BigIntegerField(max_length=12, null=True, unique=True),
        ),
    ]
