# Generated by Django 3.1 on 2020-08-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20200823_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeprofile',
            name='image',
            field=models.ImageField(default='images/profile.jpg', max_length=255, upload_to='profile_pic'),
        ),
    ]
